name: check-pr

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read Flutter version from .fvmrc
        id: fvm
        run: echo "FLUTTER_VERSION=$(jq -r '.flutter' .fvmrc)" >> "$GITHUB_OUTPUT"

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm.outputs.FLUTTER_VERSION }}

      - name: Install dependencies
        run: flutter pub get

      - name: Run code generation
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        id: test
        run: flutter test --machine > test_report.log
        continue-on-error: true

      - name: Report test results
        uses: dorny/test-reporter@v1
        if: steps.test.conclusion != 'skipped'
        with:
          name: 'flutter test'
          path: 'test_report.log'
          reporter: 'flutter-json'
          fail-on-error: 'true'